---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/data/bio.json
  label: Bio
- type: document
  path: src/data/quote.json
  label: Citazione
- type: document
  path: src/data/massages.json
  label: Massaggi
- type: document
  path: src/data/services.json
  label: Servizi
- type: document
  path: src/data/contacts.json
  label: Contatti
- type: document
  path: src/data/gallery.json
  label: Gallery
- type: document
  path: src/data/footer.json
  label: Footer
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
instant_preview: false
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: gatsby develop -H 0.0.0.0 -p 8080
  publish_command: gatsby build
  output_directory: public
  preview_command: npm run build
